### ISSUE TITLE
Accessing read_wav results with SwiftUI

### ISSUE THREAD

**Issue by angadhn** [bjnortier/whisper-ios-demo#1]
The code is great and works out of the box very easily. So, thanks for that, firstly.

Secondly, could you advise on how one can access the transcribed outputs from SwiftUI's `Text` function? I am trying to replace the "Hello World" in your app with the result but unable to figure that out.

**Comment by aimerib** [comment]
Maybe I missed something, but I still don't see how one would go about doing that though.

I also am curious about any ideas about how  to go about storing those transcriptions somewhere. If I try to assign the string in `progress` I get an Xcode error about C style callbacks not being able to capture anything from the scope. Any and all help is much appreciated, but certainly not expected. Just happy to have this to toy around with :D
