### ISSUE TITLE
App Crashes when I Press Transcribe

### ISSUE THREAD

**Issue by v-puppala** [bjnortier/whisper-ios-demo#3]
It's interesting because I don't actually get any error messages in my console. In inspect navigator however, I do get the following:

 3 instances of __NSCFString leaked:
 
 0x7ff33bd062d0
 
 0x7ff33bf0a8d0
 
 0x7ff33e812c00

**Comment by bjnortier** [comment]
Hi. I don't think the leaks are related to the crash. If you run it in Xcode you will get more info. This is a demo for people who are curious but I'm not maintaining it.
